### ISSUE TITLE
要望と読み込みミス？の報告

### ISSUE THREAD

**Issue by BALL-TYPE133** [ks-yuzu/mhrise-charm-scanner-web#1]
＜要望＞
動画だけでなくCSV形式の護石リストを読み込みできるようにして欲しいです

＜不具合＞
護石を装備ボックスで見ると33ページ(50個)＋8個で1658個あるはずなのですが、1280x720の動画を使って読み込んでみてもらったところそれより少ないのと、読み込みミスがいくつか見つかりました
ちょっと数が多すぎるので現状ではまだ特定してないのですが特定など必要なら教えて下さい

**Comment by ks-yuzu** [comment]
>＜要望＞
>動画だけでなくCSV形式の護石リストを読み込みできるようにして欲しいです

こちら準備中ですのでしばしお待ちください。

>＜不具合＞
>それより少ない

同性能の護石は除外するようになっているので、その分でしょうか？
 (重複したと思った護石が実は同じ護石だった、となると事故の元になるため)

あまりにも数が少ない場合は他の原因かもしれないので、その場合は詳細をお知らせ頂ければと思います。

> 読み込みミス

装飾品が付いている場合はその分も護石の性能扱いになってしまうことはあるのですが、
今まで 2000 個以上読み込みしている中でその他の問題が観測できていない状態です。

可能な限り対応したいと思うので、こちらも詳細をお知らせ頂けますと幸いです。

>特定など必要なら

差し支えなければ、入力動画のまま頂けましたらこちらで調査いたします。

**Comment by BALL-TYPE133** [comment]
要望を聞いてくださりありがとうございます

護石1658個→1626個（ID1は読ませるファイルミスです)は重複とのことですので総数的に大きく差はないのでそうかもしれません
こちらリストからの削除方法が分からなかったためそのままになっています、申し訳ない
読み込みミスに関してはもしかしたら勘違いしていたかもです
一応自分のブラウザに保存されているリストはこちらになります
https://www.dropbox.com/s/xw9mbuevmkqh4jt/CharmExport.txt
上述の読み込ませるファイルミス(鑑定画面の動画を入れてしまいました)の痕跡が残ってるのですがこれで参考になれば
読み込ませた動画は以下のドロップボックスのリンクのを使ったと思います
https://www.dropbox.com/s/7bjvzbxrlvshjjy/2021-07-01%2017-05-50.mp4
以上お願いします

**Comment by ks-yuzu** [comment]
遅くなりましたが、護石インポートの機能を追加しました。

護石が少ない件については、読み取り結果が
> Found 1659 charms.
になっているので、重複が除外された分によるものと思われます。

重複を含めて確認したい場合は、スキャン画面で全護石のリストが取れるので、そちらをご利用ください。
(重複護石の扱いについては、不具合と紛らわしいかと思うので、ヘルプで一言触れることにしました)

**Comment by BALL-TYPE133** [comment]
対応ありがとうございます。
サイトは「https://yuzu-k.com/」のままでいいのですよね？
インポートとヘルプの重複が見当たらず前回と同じに見えるのはブラウザの関係でしょうか…。

**Comment by BALL-TYPE133** [comment]
申し訳ない、URL変更されたのですね
GitHubトップから確認しました。

**Comment by ks-yuzu** [comment]
ややこしくてすみません。

諸事情でドメイン (URL) が 2 種類ある状態ですが、
サブドメインの方 (https://mhrise-charm-scanner.yuzu-k.com/) に統一する予定です。

ひとまずもう一方も更新しておきます。
