### ISSUE TITLE
攻勢のスキルが読み取れない

### ISSUE THREAD

**Issue by kochatece** [ks-yuzu/mhrise-charm-scanner-web#12]
![いつも使わせていただいています。ありがとうございます。
リアルタイムスキャンについてですが、攻勢のスキルが読み取れないようです。
すでに既知でしたら申し訳ございません。よろしくお願いいたします。](https://user-images.githubusercontent.com/71575894/187055876-5a9cd1e4-6bfc-46ea-9f23-2082178a7464.png)

**Comment by kochatece** [comment]
いつも使わせていただいています。ありがとうございます。
リアルタイムスキャンについてですが、攻勢のスキルが読み取れないようです。
すでに既知でしたら申し訳ございません。よろしくお願いいたします。

**Comment by ks-yuzu** [comment]
状況としては、攻勢が読み取れないというよりも、
その場所のカーソルを認識できていなさそうに見えますね...。

ウィンドウが半透明なので、背景によっては影響を受けるかもしれません。
お手数ですが、違う場所のアイテム BOX でも試していただけますでしょうか？
(参考までに、開発時はカムラのたたら場前、エルガドの雑貨屋横の BOX を主に使っていました)

他の BOX でもダメそうでしたら、輪廻サポートと同様に、感度調整をできるようにすることも検討してみようと思います。

**Comment by kerokerox** [comment]
当方も似た症状があり、BOXを変えても特に改善はせず。
問題はアイテムにロックがかかっている点だと思います。
当方ではロックの付け外しにより、問題の発生・解消が再現できました。

**Comment by ks-yuzu** [comment]
v15 の新アイコンに合わせて調整した際に同時に改善しました。
