### ISSUE TITLE
泣きシミュとの互換性について

### ISSUE THREAD

**Issue by RItme11** [ks-yuzu/mhrise-charm-scanner-web#2]
こんな便利なものが作れるのかと感動しました。

#不具合内容
UPとKOの文字列が大文字小文字で整合性が取れていないため泣きシミュ側で認識されない。 
またスキル無しの場合も無しの文字列が入るが、泣きシミュでは空白でありこれも認識されない。

**Comment by RItme11** [comment]
大文字小文字ではなく全角半角でした。

**Comment by ks-yuzu** [comment]
ご指摘ありがとうございます！
インポート・エクスポートの際の形式が泣きシミュ互換になるように調整しました。

内部形式は維持しているので、スキャン済みのデータ (ブラウザに保存されているデータ) はそのまま使えるかと思います。

**Comment by RItme11** [comment]
ありがとうございます！
