### ISSUE TITLE
護石のスキルが正常に読み取れていない

### ISSUE THREAD

**Issue by ev0tto** [ks-yuzu/mhrise-charm-scanner-web#4]
スキルの読み取りが正常に行われません。
私の動画が不具合の原因かもしれないのですが、一応報告させていただきます。

[例]
壁面移動, 体術 → 壁面移動,攻撃
耳栓,回避距離UP → 耳栓,睡眠耐性

<details><summary>screenshot</summary>

![](https://i.postimg.cc/1tvh6mhq/image.png)
</details><br/>

- [出力されたリスト](https://paste.gg/p/anonymous/3bc48118f41a4d00a3fc7e4165a22ac8/files/a877f3c193664e9eb9a4488e7e32f397/raw)
- [読み込み元の動画](https://files.catbox.moe/m5ddc4.mp4)

**Comment by ks-yuzu** [comment]
すみません、確認が遅くなりました。
たしかに正確にスキャンできていないですね...

確認したところ、switch の 30 秒キャプチャと座標のズレがありそうです。
こちらの動画はキャプボ等から録画した映像でしょうか？

その場合はリアルタイムスキャン機能をご利用いただければ、
映像のズレ補正機能が入っているので正確に読めるかと思います。

参考までに、試しに OBS 経由で動画をリアルタイムスキャンにかけてみたところ正確に読み取れました。
![image](https://user-images.githubusercontent.com/11938512/188863988-59d16d68-ff60-4a4e-98a2-100506be9ce5.png)

もし、映像の取得方法がキャプボではなければ別途対策を考えるので、
その旨お知らせいただければと思います。

**Comment by ev0tto** [comment]
返信ありがとうございます。
私も返信が遅くなり申し訳ありません。
リアルタイムスキャン機能で解決しました。
ありがとうございました。
